

sudo: required

services:
  - docker

language: go

go:
  - "1.17.x"

install:
  - git clone "https://github.com/TheCacophonyProject/cacophony-api"
  - cd cacophony-api
  - docker-compose build && docker-compose up --force-recreate -d
  - cd ..
  - docker cp db-test-seed.sql cacophony-api:/db-seed.sql
before_script:
  - ./cacophony-api/wait-for-api || { docker ps; docker logs cacophony-api; exit 1; }
  - sudo docker exec cacophony-api sh -c "sudo -i -u postgres psql cacophonytest -f/db-seed.sql"
script:
  - go mod tidy
  - git diff --exit-code || (echo "Please run 'go mod tidy' to clean up the 'go.mod' and 'go.sum' files. Your go version should match the one used with travis."; false)
  - go vet ./...
  - go test ./...
