

sudo: required

services:
  - docker

language: go

go:
  - "1.13.x"

install:
  - git clone "https://github.com/TheCacophonyProject/cacophony-api"
  - cd cacophony-api
  - ./run --isolate --background
  - cd ..
  - docker cp db-test-seed.sql cacophony-api:/db-seed.sql
before_script:
  - ./cacophony-api/wait-for-api || { docker ps; docker logs cacophony-api; exit 1; }
  - sudo docker exec cacophony-api sh -c "sudo -i -u postgres psql cacophonytest -f/db-seed.sql"
script:
  - go vet ./... && go test ./...
